import { z } from 'zod';
import sharp from 'sharp';
import type { NxAccount, NxGenerationJob, NxProviderRun, Prisma } from '@prisma/client';
import type { AdminOperationsService } from './admin-operations.service.js';
import { pagination, jsonObject } from './admin-operations.service.js';
import { estimateImagePrice } from './image-pricing.service.js';
import type { CustomerResultService } from './customer-result.service.js';
import type { AdminPrincipal } from './admin-auth.service.js';
import { AppError } from '../lib/errors.js';
const avg=(values:(number|null)[],digits=1)=>{const numbers=values.filter((n):n is number=>n!==null);return numbers.length?Number((numbers.reduce((a,b)=>a+b,0)/numbers.length).toFixed(digits)):null;};
const sum=(values:(number|null)[])=>{const numbers=values.filter((n):n is number=>n!==null);return numbers.length?numbers.reduce((a,b)=>a+b,0):null;};
const param=(query:Record<string,unknown>,key:string)=>z.string().optional().parse(query[key]);
const dates=(query:Record<string,unknown>)=>({...(query.date_from?{gte:z.coerce.date().parse(query.date_from)}:{}),...(query.date_to?{lte:z.coerce.date().parse(query.date_to)}:{})});
export class AdminUsageService {
  constructor(private readonly operations:AdminOperationsService,private readonly results:CustomerResultService){}
  private get model(){return this.operations.model;}
  async userItem(account:NxAccount){const base=await this.operations.userItem(account);const data=await this.model.read(async db=>({granted:(await db.nxCreditLedger.aggregate({where:{user_id:account.id,amount:{gt:0}},_sum:{amount:true}}))._sum.amount||0,spent:(await db.nxCreditLedger.aggregate({where:{user_id:account.id,type:'generation_spend'},_sum:{amount:true}}))._sum.amount||0,refunded:(await db.nxQuotaReservation.aggregate({where:{account_id:account.id,status:'REFUNDED'},_sum:{amount:true}}))._sum.amount||0,success:await db.nxGenerationJob.count({where:{account_id:account.id,mode:'ADVANCED',state:'COMPLETED'}}),failed:await db.nxGenerationJob.count({where:{account_id:account.id,mode:'ADVANCED',state:'FAILED'}}),basic:await db.nxGenerationJob.count({where:{account_id:account.id,mode:'BASIC'}}),subscription:await db.nxSubscription.findFirst({where:{user_id:account.id,status:'active'},orderBy:{created_at:'desc'}})}));return {account_id:account.id,email:account.email,display_name:account.display_name,account_status:account.status,signup_date:account.created_at,auth_provider:base.auth_provider,plan:base.subscription_plan,subscription_status:data.subscription?.status??null,total_ai_credits_granted:data.granted,total_ai_credits_spent:Math.abs(data.spent),total_ai_credits_refunded:data.refunded,current_remaining_credits:base.ai_remaining,successful_advanced_generations:data.success,failed_advanced_generations:data.failed,total_basic_generations:data.basic,last_activity_at:base.last_activity_at};}
  async users(query:Record<string,unknown>){const {page,page_size,skip}=pagination(query);const q=param(query,'q'),status=param(query,'status'),plan=param(query,'plan');const where:Prisma.NxAccountWhereInput={...(q?{OR:[{email:{contains:q.trim(),mode:'insensitive'}},{display_name:{contains:q.trim(),mode:'insensitive'}},{id:{contains:q.trim(),mode:'insensitive'}}]}:{}),...(status?{status}:{}),created_at:dates(query)};
    if(plan){const plans=await this.model.read(db=>db.nxPlan.findMany({where:{code:plan}}));const subscriptions=await this.model.read(db=>db.nxSubscription.findMany({where:{status:'active',plan_id:{in:plans.map(row=>row.id)}}}));where.id={in:subscriptions.map(row=>row.user_id)};}
    const direction=z.enum(['asc','desc']).default('desc').parse(query.direction),sort=param(query,'sort')||'signup_date';
    const column=({signup_date:'created_at',email:'email',status:'status',last_activity:'last_activity_at'} as const)[sort as 'signup_date']||'created_at';
    const total=await this.model.read(db=>db.nxAccount.count({where}));let rows: NxAccount[];
    if(sort==='credits_remaining') { // SQL computed balance; order before pagination.
      const all=await this.model.read(db=>db.nxAccount.findMany({where}));all.sort((a,b)=>((a.ai_quota_total-a.ai_quota_used-a.ai_quota_reserved)-(b.ai_quota_total-b.ai_quota_used-b.ai_quota_reserved))*(direction==='asc'?1:-1));rows=all.slice(skip,skip+page_size);
    }else rows=await this.model.read(db=>db.nxAccount.findMany({where,orderBy:{[column]:direction},skip,take:page_size}));
    return {users:await Promise.all(rows.map(row=>this.userItem(row))),page,page_size,total,pages:Math.max(1,Math.ceil(total/page_size))};}
  async user(id:string){const account=await this.operations.account(id);const data=await this.model.read(async db=>({identities:await db.nxAuthIdentity.findMany({where:{account_id:id}}),subscription:await db.nxSubscription.findFirst({where:{user_id:id,status:'active'},orderBy:{created_at:'desc'}}),recent:await db.nxGenerationJob.findMany({where:{account_id:id},orderBy:{created_at:'desc'},take:10})}));const plan=data.subscription?await this.model.read(db=>db.nxPlan.findUnique({where:{id:data.subscription!.plan_id}})):null;return {user:await this.userItem(account),identities:data.identities.map(({provider,email,created_at,last_login_at})=>({provider,email,created_at,last_login_at})),subscription:data.subscription?{id:data.subscription.id,plan:plan?.code,status:data.subscription.status,starts_at:data.subscription.starts_at,current_period_end:data.subscription.current_period_end}:null,recent_generations:await Promise.all(data.recent.map(job=>this.generationItem(job)))};}
  async credits(id:string,query:Record<string,unknown>){const account=await this.operations.account(id);const {balance,...data}=await this.operations.credits(id,query);return {...data,summary:await this.userItem(account)};}
  runItem(run:NxProviderRun){const {account_id,provider_usage_raw_json,...data}=run;return {...data,provider_usage:jsonObject(provider_usage_raw_json),api_price_estimate:estimateImagePrice(run)};}
  async generationItem(job:NxGenerationJob){const base=await this.operations.generationItem(job);const data=await this.model.read(async db=>({run:await db.nxProviderRun.findFirst({where:{generation_job_id:job.id},orderBy:{created_at:'desc'}}),result:await db.nxResult.findUnique({where:{job_id:job.id}})}));const {run,result}=data;const available=result&&!result.deleted_at&&await this.operations.assets.exists(result.storage_path);
    return {job_id:job.id,account_id:job.account_id,user_email:base.user_email,guest_id:job.guest_id,mode:job.mode,experience_id:job.experience_id,template_id:job.template_id||null,status:job.state,credit_state:base.credit_state,provider:run?.provider_name||job.provider,model:run?.provider_model||job.model,upstream_account:run?.provider_account_label||run?.provider_account_id||null,
      requested_model:run?.requested_model||job.model,provider_reported_model:run?.provider_reported_model??null,router_request_id:run?.router_request_id??null,upstream_request_id:run?.upstream_request_id??null,routing_strategy:run?.routing_strategy??null,attempt_count:run?.attempt_count??null,retry_count:run?.retry_count??null,failover_count:run?.failover_count??null,input_tokens:run?.input_tokens??null,output_tokens:run?.output_tokens??null,total_tokens:run?.total_tokens??null,router_duration_ms:run?.router_duration_ms??null,application_duration_ms:run?.application_duration_ms??null,usage_available:Boolean(run?.provider_usage_raw_json),duration_ms:run?.total_duration_ms??(base.duration_seconds===null?null:Math.round(base.duration_seconds*1000)),created_at:job.created_at,started_at:job.started_at,finished_at:job.finished_at,
      result_id:result?.id??null,result_image_url:available?`/api/admin/usage/generations/${job.id}/result/image`:null,result_download_url:available?`/api/admin/usage/generations/${job.id}/result/download`:null,result_deleted_at:result?.deleted_at??null,api_price_estimate:run?estimateImagePrice(run):null};}
  async generations(query:Record<string,unknown>,id?:string){if(id)await this.operations.account(id);const {page,page_size,skip}=pagination(query);const mode=z.enum(['CLASSIC','BASIC','ADVANCED']).optional().parse(query.mode),status=param(query,'status');const where:Prisma.NxGenerationJobWhereInput={...(id?{account_id:id}:{}),...(mode?{mode}:{}),...(status?{state:status.toUpperCase()}:{}),created_at:dates(query)};
    const user=param(query,'user');if(user){const accounts=await this.model.read(db=>db.nxAccount.findMany({where:{OR:[{email:{contains:user.trim(),mode:'insensitive'}},{id:{contains:user.trim(),mode:'insensitive'}}]}}));where.account_id={in:accounts.map(row=>row.id)};}
    const provider=param(query,'provider'),model=param(query,'model'),account=param(query,'provider_account_ref'),strategy=param(query,'routing_strategy');
    if(provider||model||account||strategy){const runWhere:Prisma.NxProviderRunWhereInput={...(provider?{provider_name:provider}:{}),...(model?{provider_model:model}:{}),...(account?{provider_account_id:account}:{}),...(strategy?{routing_strategy:strategy}:{})};const runs=await this.model.read(db=>db.nxProviderRun.findMany({where:runWhere,select:{generation_job_id:true}}));where.id={in:runs.map(row=>row.generation_job_id)};}
    const data=await this.model.read(async db=>({total:await db.nxGenerationJob.count({where}),rows:await db.nxGenerationJob.findMany({where,orderBy:{created_at:'desc'},skip,take:page_size})}));return {generations:await Promise.all(data.rows.map(row=>this.generationItem(row))),page,page_size,total:data.total,pages:Math.max(1,Math.ceil(data.total/page_size))};}
  async generation(id:string){const base=await this.operations.generation(id);const job=await this.model.read(db=>db.nxGenerationJob.findUniqueOrThrow({where:{id}}));const data=await this.model.read(async db=>({runs:await db.nxProviderRun.findMany({where:{generation_job_id:id},orderBy:{created_at:'asc'}}),ledger:await db.nxCreditLedger.findMany({where:{related_generation_id:id},orderBy:{created_at:'asc'}})}));return {generation:await this.generationItem(job),error_code:base.error_code,error_message:base.error_message,events:base.events,claims:base.claims,provider_runs:data.runs.map(run=>this.runItem(run)),credit_history:data.ledger.map(({id,type,amount,reason,created_at})=>({id,type,amount,reason,created_at}))};}
  private async runs(){return this.model.read(db=>db.nxProviderRun.findMany());}
  async overview(){
    const base=await this.operations.overview(),runs=await this.runs();
    const aiWhere:Prisma.NxGenerationJobWhereInput={mode:{in:['BASIC','ADVANCED']}};
    const ai_jobs=await this.model.read(db=>db.nxGenerationJob.count({where:aiWhere}));
    const advanced_jobs=await this.model.read(db=>db.nxGenerationJob.count({where:{mode:'ADVANCED'}}));
    const usage=new Set(runs.filter(row=>row.provider_usage_raw_json!==null).map(row=>row.generation_job_id)).size;
    const accounts=new Set(runs.filter(row=>row.provider_account_id!==null||row.provider_account_label!==null).map(row=>row.generation_job_id)).size;
    const providers=new Map<string,number>();for(const row of runs)providers.set(row.provider_name,(providers.get(row.provider_name)||0)+1);
    const refunded=(await this.model.read(db=>db.nxQuotaReservation.aggregate({where:{status:'REFUNDED'},_sum:{amount:true}})))._sum.amount||0;
    return {total_users:base.total_users,active_users:base.active_users,successful_generations:base.successful_generations,failed_generations:base.failed_generations,
      credits_spent:base.ai_credits_consumed,credits_refunded:refunded,ai_jobs,advanced_jobs,provider_usage_jobs:usage,provider_account_jobs:accounts,
      usage_coverage_percent:ai_jobs?Number((usage*100/ai_jobs).toFixed(1)):0,
      provider_account_coverage_percent:ai_jobs?Number((accounts*100/ai_jobs).toFixed(1)):0,
      provider_distribution:[...providers].map(([provider,jobs])=>({provider,jobs})).sort((a,b)=>b.jobs-a.jobs)};
  }
  async providerAccounts(){const groups=new Map<string,NxProviderRun[]>();for(const run of await this.runs())if(run.provider_account_id!==null||run.provider_account_label!==null){const key=JSON.stringify([run.provider_account_label,run.provider_account_id]);groups.set(key,[...(groups.get(key)||[]),run]);}return [...groups.values()].map(rows=>({provider_account_label:rows[0].provider_account_label,provider_account_id:rows[0].provider_account_id,jobs_count:rows.length,success_count:rows.filter(row=>row.upstream_status==='SUCCEEDED').length,failed_count:rows.filter(row=>row.upstream_status!=='SUCCEEDED').length,last_used_at:new Date(Math.max(...rows.map(row=>row.created_at.getTime()))),total_tokens:sum(rows.map(row=>row.total_tokens)),average_duration_ms:avg(rows.map(row=>row.total_duration_ms))})).sort((a,b)=>b.jobs_count-a.jobs_count);}
  async providerOverview(){
    const runs=await this.runs(),accounts=await this.providerAccounts();
    const jobs=await this.model.read(db=>db.nxGenerationJob.findMany({where:{mode:{in:['BASIC','ADVANCED']}},select:{id:true,state:true}}));
    const advanced=await this.model.read(db=>db.nxGenerationJob.count({where:{mode:'ADVANCED'}}));
    return {total_ai_jobs:jobs.length,total_advanced_jobs:advanced,completed:jobs.filter(job=>job.state==='COMPLETED').length,
      failed:jobs.filter(job=>job.state==='FAILED').length,
      refunded:await this.model.read(db=>db.nxQuotaReservation.count({where:{status:'REFUNDED',job_id:{in:jobs.map(job=>job.id)}}})),
      average_duration_ms:avg(runs.map(run=>run.router_duration_ms)),
      jobs_with_provider_usage:new Set(runs.filter(run=>run.provider_usage_raw_json).map(run=>run.generation_job_id)).size,
      jobs_with_provider_account_info:new Set(runs.filter(run=>run.provider_account_id||run.provider_account_label).map(run=>run.generation_job_id)).size,
      configured_strategy:null,observed_strategy_hints:[...new Set(runs.map(run=>run.provider_strategy_hint).filter((hint):hint is string=>!!hint))].sort(),
      routing_strategy_known:false,can_prove_round_robin:false,
      account_distribution_evidence:accounts.length>1?'multiple_upstream_accounts_observed':accounts.length===1?'single_upstream_account_observed':'upstream_account_unavailable',
      strategy_message:'Observed upstream accounts do not prove a routing strategy. Router configuration and rotation remain controlled by the provider.',
      total_input_tokens:sum(runs.map(run=>run.input_tokens)),total_output_tokens:sum(runs.map(run=>run.output_tokens)),
      total_tokens:sum(runs.map(run=>run.total_tokens)),average_attempts:avg(runs.map(run=>run.attempt_count),2),
      provider_cost_available:runs.some(run=>run.provider_reported_cost!==null)};
  }
  private async result(id:string){const result=await this.model.read(db=>db.nxResult.findUnique({where:{job_id:id}}));if(!result||result.deleted_at)throw new AppError(404,'RESULT_NOT_FOUND','Result unavailable.');return result;}
  async photo(id:string,thumbnail:boolean){const result=await this.result(id);const bytes=await this.results.bytes(result);return {result,bytes:thumbnail?await sharp(bytes).resize(300,450,{fit:'inside',withoutEnlargement:true}).jpeg({quality:80}).toBuffer():bytes,contentType:thumbnail?'image/jpeg':result.content_type};}
  async deletePhoto(id:string,actor:AdminPrincipal){const result=await this.result(id);const job=await this.model.read(db=>db.nxGenerationJob.findUniqueOrThrow({where:{id}}));const identity={account:job.account_id?{id:job.account_id}:null,guest:job.guest_id?{id:job.guest_id}:null} as Parameters<CustomerResultService['delete']>[1];const response=await this.results.delete(result.id,identity,"admin");await this.model.transaction(tx=>this.model.audit(tx,actor,'result_photo_deleted','result',result.id,'',{job_id:id}));return response;}
}
