import { AppError } from '../lib/errors.js';

// Preserve the CURRENT application's art direction during the runtime migration.
// Ornaments are camera effects in the current flow and never enter this prompt.
export const STYLE_PRINCIPLE = 'Adapt this frame design language to the visual world of the selected experience so that the frame and generated scene appear intentionally art-directed together.';
export const COMPOSITION_RULES = 'Create one coherent 2:3 vertical print composition. Keep the subject readable, with essential face and body details inside safe margins. Integrate the frame into the scene rather than adding a fixed border. No stretching.';
export const BRANDING_RULES = 'The required footer lettering below is an explicit exception to any earlier instruction forbidding text or watermarks. Fill the branding box or footer within the lower part of the frame with the exact text "NXBooth" and a smaller line underneath reading "Powered by GenNexByte". Integrate both lines into that frame area with clear, legible lettering and materials appropriate to the selected experience. Keep all branding inside the frame\'s footer, without covering the subject. Do not leave the branding box empty, add a separate black panel, duplicate the branding, or add any other text.';

export function composeAdvancedPrompt(experiencePrompt: string, frameStylePrompt: string): string {
  if (!experiencePrompt.trim() || !frameStylePrompt.trim()) throw new AppError(422, 'ADVANCED_SELECTION_INVALID', 'Experience and frame prompts are required');
  return [
    'EXPERIENCE — PRIMARY VISUAL AUTHORITY\n' + experiencePrompt.trim(),
    'FRAME STYLE\n' + frameStylePrompt.trim() + '\n' + STYLE_PRINCIPLE,
    'PRINT AND COMPOSITION\n' + COMPOSITION_RULES,
    'FRAME FOOTER BRANDING\n' + BRANDING_RULES,
  ].join('\n\n');
}

export function composeBasicPrompt(templateName: string, templateDescription: string): string {
  if (!templateName.trim() || !templateDescription.trim()) throw new AppError(422, 'BASIC_TEMPLATE_INVALID', 'Template direction is required');
  return [
    'TEMPLATE — IMMUTABLE BASE IMAGE\nPerform a localized identity edit of Image 1 using the person in Image 2. Image 1 supplies the scene, hair, skin rendering, body and head placement; Image 2 supplies recognizable personal resemblance cues. Create a subtle template-dominant facial resemblance, rather than a literal anatomical replacement. Let the face suggest the person in Image 2 while retaining the model-like facial presentation of Image 1. Do not generate a new scene or paste the source photo onto the template.',
    `SELECTED TEMPLATE\nName: ${templateName.trim()}\nDescription: ${templateDescription.trim()}\nThis description identifies the scene, not the facial identity to retain.`,
    'LOCKED TEMPLATE APPEARANCE\nPreserve the hair exactly as Image 1: hairstyle, hairline, length, volume, color, and texture. Preserve the facial skin tone and complexion exactly as Image 1, including its brightness, undertone, texture, highlights, shadows, and color grading. Do not import the skin color, exposure, or lighting from Image 2. Keep the overall head size, center position, camera perspective, and head pose from Image 1. Retain the template overall facial silhouette and broad proportions, with only gentle contour adjustments needed for resemblance. Do not copy the source cheek width, jaw width, chin outline, or complete facial contour literally.',
    'SUBJECT IDENTITY — SUBTLE TEMPLATE-DOMINANT RESEMBLANCE\nBring in the recognizable source eye shape, eyelid character, eyebrows, and lip shape gently, at the template scale and pose. Preserve the source eye shape without enlarging, narrowing, lifting, beautifying, or substituting generic eyes. Keep the template broad facial presentation and relaxed expression, without forcing a smile that changes the source eye shape. Adopt the source nose gently and naturally, without exaggerating, sharpening, or slimming it. Keep the template cheek fullness, jaw structure, chin silhouette, and head outline predominantly intact; allow only small, smooth changes that suggest the source person. Do not reproduce the source full facial anatomy or create an exact copied face. The result should resemble the source person subtly while still looking naturally like the designed template portrait.',
    'NATURAL VISUAL MERGE\nRender the resemblance using the template skin material, warm or cool scene lighting, exposure, shading, and photographic finish. Use source features as shape cues, not as pasted pixels or source camera lighting. Make transitions across the temples, cheeks, jaw, hairline, and neck soft and anatomically coherent. Avoid a sharply outlined transplanted face, heavy source jaw definition, cutout edges, or a webcam face stamped onto the model. Keep the face readable without blurring the eyes or losing the source distinctive eye and lip cues.',
    'EYEWEAR COMPATIBILITY\nIf Image 2 visibly contains eyeglasses, retain one coherent pair with the recognizable frame design from Image 2. Fit the glasses naturally to the blended template face at its existing scale and pose. Render lens transparency, reflections, highlights, and contact shadows using the lighting of Image 1. Preserve the visible source eyes behind the lenses; do not invent larger eyes, inherit the template actor eyes, transfer source-photo glare, or darken the face. Do not add a second pair of glasses. If Image 2 has no eyeglasses, do not introduce new eyewear; preserve any eyewear already in Image 1.',
    'PRINT AND COMPOSITION\nReturn one complete edited Image 1 at its original aspect ratio and pixel dimensions. Preserve the original framing and all four edges. Keep the exact canvas, composition, neck, body, costume, background, decorative frame, title, and footer. Keep the head at the template scale and position with a gentle, coherent facial resemblance, preserving the template-dominant silhouette. No new crop, camera angle, head tilt, zoom, subject enlargement, inset portrait, pasted face, or additional person. Blend the edited face naturally into the template lighting and unchanged hair and neck.',
    'FRAME FOOTER BRANDING\nPreserve every existing letter and graphic including NXBooth and Powered by GenNexByte exactly as supplied in Image 1. Never add a black panel, duplicate logo, new text, or additional branding.',
  ].join('\n\n');
}
