import type { Request, RequestHandler } from 'express';
import { z } from 'zod';
import type { AdminAuthService, AdminPrincipal } from '../services/admin-auth.service.js';
import { adminCookie } from '../services/admin-auth.service.js';
import type { AdminCatalogService } from '../services/admin-catalog.service.js';
import type { AdminOperationsService } from '../services/admin-operations.service.js';
import type { AdminUsageService } from '../services/admin-usage.service.js';
import type { AdminPreviewService } from '../services/admin-preview.service.js';
export type NativeAdminServices = { auth:AdminAuthService; catalog:AdminCatalogService; operations:AdminOperationsService; usage:AdminUsageService; previews:AdminPreviewService };
const id=(req:Request,key='id')=>z.string().min(1).max(128).parse(req.params[key]);
export function adminController(services:NativeAdminServices){
  const {auth,catalog,operations,usage,previews}=services;
  const action=(role:string,fn:(req:Request,actor:AdminPrincipal)=>Promise<unknown>,status=200):RequestHandler=>async(req,res)=>{const actor=await auth.resolve(req.cookies||{},req.get('x-admin-token'));auth.requireRole(actor,role);const data=await fn(req,actor);if(status===204)res.status(204).end();else res.status(status).json(data);};
  const asset=(fn:(req:Request)=>Promise<string>):RequestHandler=>async(req,res)=>{const actor=await auth.resolve(req.cookies||{},req.get('x-admin-token'));auth.requireRole(actor,'content_manager');res.type('png').sendFile(await fn(req));};
  const confirm=(req:Request)=>z.object({confirm:z.literal(true)}).parse(req.body);
  const cookie={httpOnly:true,secure:auth.config.cookieSecure,sameSite:'lax' as const,path:'/'};
  const login:RequestHandler=async(req,res)=>{const body=z.object({token:z.string().min(1).max(512)}).parse(req.body);res.cookie(adminCookie,await auth.login(body.token),{...cookie,maxAge:auth.config.sessionDays*86400000});res.json({authenticated:true});};
  const logout:RequestHandler=async(req,res)=>{await auth.logout(req.cookies||{});res.clearCookie(adminCookie,cookie).json({authenticated:false});};
  const photo=(download=false):RequestHandler=>async(req,res)=>{const actor=await auth.resolve(req.cookies||{},req.get('x-admin-token'));auth.requireRole(actor,'operator');const data=await usage.photo(id(req),req.query.thumbnail==='true'&&!download);res.type(data.contentType);if(download)res.attachment(`photobooth-${data.result.id}.${data.contentType==='image/png'?'png':data.contentType==='image/jpeg'?'jpg':'webp'}`);res.send(data.bytes);};
  return {login,logout,action,asset,photo,
    experiences:action('content_manager',()=>catalog.listExperiences()),createExperience:action('content_manager',(req,actor)=>catalog.createExperience(req.body,actor),201),patchExperience:action('content_manager',(req,actor)=>catalog.patchExperience(id(req),req.body,actor)),deleteExperience:action('content_manager',(req,actor)=>catalog.deleteExperience(id(req),actor),204),
    templates:action('content_manager',()=>catalog.listTemplates()),createTemplate:action('content_manager',(req,actor)=>catalog.createTemplate(req.body,actor),201),patchTemplate:action('content_manager',(req,actor)=>catalog.patchTemplate(id(req),req.body,actor)),deleteTemplate:action('content_manager',(req,actor)=>catalog.deleteTemplate(id(req),actor),204),
    publish:action('content_manager',(req,actor)=>{confirm(req);return catalog.publishReady(actor);}),
    layouts:action('content_manager',()=>catalog.layouts()),createLayout:action('content_manager',req=>catalog.createLayout(req.body),201),patchLayout:action('content_manager',req=>catalog.patchLayout(id(req),req.body)),removeLayout:action('content_manager',req=>catalog.patchLayout(id(req),{enabled:false})),frame:action('content_manager',req=>catalog.replaceFrame(id(req),req.file)),
    presets:action('content_manager',req=>catalog.presets(id(req,'kind'))),createPreset:action('content_manager',req=>catalog.savePreset(id(req,'kind'),null,req.body),201),patchPreset:action('content_manager',req=>catalog.savePreset(id(req,'kind'),id(req),req.body)),
    sources:action('content_manager',()=>previews.sources()),replaceSource:action('content_manager',(req,actor)=>previews.replaceSource(id(req),req.file,actor)),sourceImage:asset(req=>previews.sourceAsset(id(req))),preview:action('content_manager',(req,actor)=>previews.enqueue(id(req),actor),202),previewJob:action('content_manager',req=>previews.job(id(req))),previewBatch:action('content_manager',(req,actor)=>{const body=z.object({confirm:z.literal(true),source_id:z.string().default('portrait-default')}).parse(req.body);return previews.batch(actor,body.source_id);},202),
    overview:action('operator',()=>operations.overview()),users:action('operator',req=>operations.users(req.query)),user:action('operator',req=>operations.user(id(req))),credits:action('operator',req=>operations.credits(id(req),req.query)),userGenerations:action('operator',async req=>(await operations.generations({page_size:100},id(req))).jobs),sessions:action('operator',req=>operations.sessions(id(req))),userAudit:action('operator',req=>operations.audit({},id(req))),status:action('operator',(req,actor)=>operations.status(id(req),req.body,actor)),revokeSessions:action('operator',(req,actor)=>operations.status(id(req),req.body,actor,true)),adjust:action('operator',(req,actor)=>operations.adjust(id(req),req.body,actor)),ledger:action('operator',req=>operations.credits(null,req.query)),
    plans:action('operator',()=>operations.plans()),createPlan:action('superadmin',(req,actor)=>operations.savePlan(null,req.body,actor),201),patchPlan:action('superadmin',(req,actor)=>operations.savePlan(id(req),req.body,actor)),subscriptions:action('operator',()=>operations.subscriptions()),subscription:action('operator',(req,actor)=>operations.subscription(id(req),req.body,actor)),generations:action('operator',req=>operations.generations(req.query)),generation:action('operator',req=>operations.generation(id(req))),revokeClaim:action('operator',(req,actor)=>operations.revokeClaim(id(req),req.body,actor)),audit:action('operator',req=>operations.audit(req.query)),adminUsers:action('superadmin',()=>operations.adminUsers()),createAdmin:action('superadmin',(req,actor)=>operations.saveAdmin(null,req.body,actor),201),patchAdmin:action('superadmin',(req,actor)=>operations.saveAdmin(id(req),req.body,actor)),settings:action('operator',async()=>operations.safeSettings),
    usageOverview:action('operator',()=>usage.overview()),usageUsers:action('operator',req=>usage.users(req.query)),usageUser:action('operator',req=>usage.user(id(req))),usageCredits:action('operator',req=>usage.credits(id(req),req.query)),usageUserGenerations:action('operator',req=>usage.generations(req.query,id(req))),usageGenerations:action('operator',req=>usage.generations(req.query)),usageGeneration:action('operator',req=>usage.generation(id(req))),providerOverview:action('operator',()=>usage.providerOverview()),providerAccounts:action('operator',()=>usage.providerAccounts()),deletePhoto:action('operator',(req,actor)=>{confirm(req);return usage.deletePhoto(id(req),actor);}),
  };
}
