/** Disposable native Express preview against the dedicated admin test database. */
import {PrismaClient} from '@prisma/client';
import {PrismaPg} from '@prisma/adapter-pg';
import {CustomerAccountService} from '../src/services/customer-account.service.js';
import {CustomerAccountModel} from '../src/models/customer-account.model.js';
import {AdminAuthService} from '../src/services/admin-auth.service.js';
import {AdminAuthModel} from '../src/models/admin-auth.model.js';
import {AdminDataModel} from '../src/models/admin-data.model.js';
import {AdminOperationsService} from '../src/services/admin-operations.service.js';
import {AdminUsageService} from '../src/services/admin-usage.service.js';
import {AdminCatalogService} from '../src/services/admin-catalog.service.js';
import type {AdminPreviewService} from '../src/services/admin-preview.service.js';
import {CatalogAssetsService} from '../src/services/catalog-assets.service.js';
import {CustomerResultService} from '../src/services/customer-result.service.js';
import {CustomerResultModel} from '../src/models/customer-result.model.js';
import {CustomerCatalogService} from '../src/services/customer-catalog.service.js';
import {CustomerCatalogModel} from '../src/models/customer-catalog.model.js';
import {createMigrationApp} from '../src/migration-app.js';
const connectionString=process.env.ADMIN_TEST_DATABASE_URL;
if(!connectionString||new URL(connectionString).pathname!=='/nxbooth_express_admin_auth_test')throw new Error('Disposable test database required');
const db=new PrismaClient({adapter:new PrismaPg({connectionString})});
await db.nxAdminUser.update({where:{id:'auth-operator'},data:{role:'operator',is_active:true}});
await db.nxAdminUser.update({where:{id:'auth-content'},data:{is_active:true}});
await db.nxAccount.update({where:{id:'auth-content'},data:{status:'active'}});
const root='/srv/photobooth/tmp/admin-signin-test',assets=new CatalogAssetsService([root],root),model=new AdminDataModel(db);
const account=new CustomerAccountService(new CustomerAccountModel(db),{sessionSecret:'synthetic-browser-preview-key',sessionDays:1,cookieSecure:false},{async verify(credential){if(credential!=='synthetic-google-verified')throw new Error('Synthetic credential required');return{subject:'synthetic-owner',email:'owner@example.invalid',name:'Fixture owner',avatar_url:null};}});
const auth=new AdminAuthService(new AdminAuthModel(db),account.signer,{token:'legacy-token-ignored',defaultRole:'superadmin',sessionDays:1,cookieSecure:false});
const operations=new AdminOperationsService(model,assets,{environment:'test',ai_provider:'not_connected',google_configured:true,upload_max_bytes:12000000,upload_min_dimension:256,upload_max_dimension:8000,admin_default_role:'superadmin'});
const catalog=new AdminCatalogService(model,assets,{templatesDir:root,tmpDir:root,minDimension:256,maxDimension:8000});
const results=new CustomerResultService(new CustomerResultModel(db),{resultsDir:root,claimHours:1,publicOrigin:'http://localhost:5194',production:false});
const admin={auth,operations,catalog,usage:new AdminUsageService(operations,results),previews:{sources:async()=>[]} as unknown as AdminPreviewService};
const app=createMigrationApp(new CustomerCatalogService(new CustomerCatalogModel(db),assets),{corsOrigins:['http://localhost:5194','http://127.0.0.1:5194'],admin},account);
const server=app.listen(5196,'127.0.0.1',()=>console.log('Disposable admin Express preview ready on 5196'));
process.on('SIGTERM',()=>server.close(async()=>{await db.$disconnect();process.exit(0)}));
