import 'dotenv/config';
import { z } from 'zod';

// Preserve the existing registry. Object storage is explicitly enabled by env.
export const migrationConfigSchema = z.object({
  DATABASE_URL: z.string().min(1),
  PORT: z.coerce.number().int().min(1).max(65535).default(8081),
  HOST: z.string().default('127.0.0.1'),
  TRUST_PROXY: z.enum(['true','false']).default('false').transform(value=>value==='true'),
  CORS_ORIGINS: z.string().default('http://localhost:5173').transform(value => value.split(',').map(item => item.trim()).filter(Boolean)),
  RUNTIME_DIR: z.string().default('/srv/photobooth'),
  TEMPLATES_DIR: z.string().default('/srv/photobooth/templates'),
  STORAGE_BACKEND: z.enum(['filesystem', 'minio']).default('filesystem'),
  MINIO_ENDPOINT: z.string().default(''),
  MINIO_PORT: z.coerce.number().int().min(1).max(65535).default(9000),
  MINIO_USE_SSL: z.enum(['true', 'false']).default('false').transform(value => value === 'true'),
  MINIO_ACCESS_KEY: z.string().default(''),
  MINIO_SECRET_KEY: z.string().default(''),
  MINIO_BUCKET: z.string().default(''),
  MINIO_REGION: z.string().default('us-east-1'),
  MINIO_SIGNED_URLS_ENABLED: z.enum(['true','false']).default('false').transform(value => value==='true'),
  MINIO_PUBLIC_ENDPOINT: z.string().default(''),
  MINIO_PUBLIC_PORT: z.coerce.number().int().min(1).max(65535).default(443),
  MINIO_PUBLIC_USE_SSL: z.enum(['true','false']).default('true').transform(value => value==='true'),
  MINIO_PRESIGNED_URL_TTL_SECONDS: z.coerce.number().int().min(1).max(3600).default(300),
  SESSION_SECRET_KEY: z.string().default(''),
  SESSION_DAYS: z.coerce.number().int().min(1).max(365).default(30),
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  COOKIE_SECURE: z.enum(['true', 'false']).default('true').transform(value => value === 'true'),
  RESULT_CLAIM_TTL_HOURS: z.coerce.number().int().min(1).max(168).default(24),
  KIOSK_RESET_SECONDS: z.coerce.number().int().min(15).max(3600).default(90),
  KIOSK_API_KEY: z.union([z.literal(''),z.string().min(32)]).default(''),
  NATIVE_KIOSK_ENABLED: z.enum(['true','false']).default('false').transform(value => value === 'true'),
  KIOSK_PHOTO_SESSION_TTL_SECONDS: z.coerce.number().int().min(60).max(604800).default(86400),
  KIOSK_GENERATION_LIMIT: z.coerce.number().int().min(1).max(100).default(3),
  RESULT_CLAIM_PUBLIC_BASE_URL: z.string().default(''),
  IMAGE_ENGINE_NORMALIZE_URL: z.string().default(''),
  AI_ENGINE_API_KEY: z.string().default(''),
  UPLOAD_MAX_BYTES: z.coerce.number().int().positive().default(12 * 1024 * 1024),
  UPLOAD_RETENTION_HOURS: z.coerce.number().int().min(1).max(168).default(24),
  REDIS_URL: z.string().default('redis://127.0.0.1:6379/15'),
  GENERATION_QUEUE_BACKEND: z.enum(['redis','postgres']).default('redis'),
  WORKER_MAX_ATTEMPTS: z.coerce.number().int().min(1).max(20).default(3),
  QUEUE_NAME: z.string().min(1).default('nxbooth:express:candidate:generation'),
  PREVIEW_QUEUE_NAME: z.string().min(1).default('nxbooth:express:candidate:preview'),
  IMAGE_ENGINE_BASE_URL: z.string().default(''),
  AI_PROVIDER: z.enum(['none', '9router']).default('none'),
  NINEROUTER_BASE_URL: z.string().default(''),
  NINEROUTER_API_KEY: z.string().default(''),
  BASIC_MODEL_EXPERIENCE_ID: z.string().min(1).default('mini-me'),
  NINEROUTER_TIMEOUT_SECONDS: z.coerce.number().positive().max(600).default(300),
  PROVIDER_RESULT_ORIGINS: z.string().default('').transform(value => value.split(',').map(item => item.trim()).filter(Boolean)),
  GOOGLE_CLIENT_ID: z.string().default(''),
  ADMIN_TOKEN: z.string().default(''),
  ADMIN_DEFAULT_ROLE: z.enum(['superadmin', 'operator', 'content_manager']).default('superadmin'),
  UPLOAD_MIN_DIMENSION: z.coerce.number().int().positive().default(256),
  UPLOAD_MAX_DIMENSION: z.coerce.number().int().positive().default(8000),
  UPLOAD_CLEANUP_INTERVAL_SECONDS: z.coerce.number().int().min(60).max(86400).default(3600),
}).refine(value => value.NODE_ENV !== 'production' || Boolean(value.SESSION_SECRET_KEY.trim()), { message: 'SESSION_SECRET_KEY is required in production', path: ['SESSION_SECRET_KEY'] })
  .refine(value => value.STORAGE_BACKEND !== 'minio' || Boolean(value.MINIO_ENDPOINT.trim() && value.MINIO_ACCESS_KEY.trim() && value.MINIO_SECRET_KEY && /^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/.test(value.MINIO_BUCKET)), { message: 'MinIO endpoint, credentials and a valid bucket are required', path: ['STORAGE_BACKEND'] })
  .refine(value => !value.NATIVE_KIOSK_ENABLED || value.KIOSK_API_KEY.length >= 32,{ message: 'A Kiosk API key is required when native Kiosk is enabled',path: ['KIOSK_API_KEY'] })
  .refine(value => !value.MINIO_SIGNED_URLS_ENABLED || value.STORAGE_BACKEND==='minio' && /^[A-Za-z0-9][A-Za-z0-9.-]*$/.test(value.MINIO_PUBLIC_ENDPOINT) &&
    (value.NODE_ENV!=='production' || value.MINIO_PUBLIC_USE_SSL && value.MINIO_PUBLIC_ENDPOINT!=='localhost' && !/^\d+\.\d+\.\d+\.\d+$/.test(value.MINIO_PUBLIC_ENDPOINT)),
    { message: 'Signed delivery requires MinIO and a configured public hostname (HTTPS in production)',path: ['MINIO_PUBLIC_ENDPOINT'] });
