#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Photobooth AI — migrate an existing checkout into the canonical /opt path.
#
# Run AFTER scripts/bootstrap_vps.sh has created /opt/photobooth.
# This script needs NO privileges.
#
# WHAT IT DOES
#   1. verifies /opt/photobooth + /srv/photobooth exist and are writable
#   2. copies the project source into /opt/photobooth (rsync, excludes
#      build artefacts, .venv, node_modules and .env)
#   3. writes /opt/photobooth/.env from the source .env so no secret is ever
#      committed or printed
#   4. re-points the runtime at the HOST /srv/photobooth tree via bind mounts
#      (compose override), replacing the named volume
#   5. validates the new compose config and reports the exact next commands
#
# WHAT IT DOES NOT DO
#   - it does NOT stop, start, remove or recreate any container
#   - it does NOT touch another project's container, network or volume
#   - it does NOT run docker system prune
#   - it does NOT delete the source checkout
#
# The old stack keeps running until you explicitly bring the new one up, so
# there is no downtime window and rollback is simply "keep using the old one".
#
# USAGE:
#   bash /home/mahez/photoboothai/scripts/migrate_to_opt.sh [SOURCE_DIR]
# ---------------------------------------------------------------------------
set -euo pipefail

SRC="${1:-/home/mahez/photoboothai}"
APP_DIR="/opt/photobooth"
RUNTIME_DIR="/srv/photobooth"

echo "== Photobooth AI migration =="
echo "   source : $SRC"
echo "   target : $APP_DIR"
echo

# --- 1. preflight ----------------------------------------------------------
if [[ "$(id -u)" -eq 0 ]]; then
  echo "WARN: running as root; files will be root-owned. Prefer the deploy user." >&2
fi

for dir in "$SRC" "$APP_DIR" "$RUNTIME_DIR"; do
  if [[ ! -d "$dir" ]]; then
    echo "ERROR: missing directory: $dir" >&2
    echo "       Run scripts/bootstrap_vps.sh with sudo first." >&2
    exit 1
  fi
done

for dir in "$APP_DIR" "$RUNTIME_DIR"; do
  if [[ ! -w "$dir" ]]; then
    echo "ERROR: not writable by $(id -un): $dir" >&2
    echo "       Re-run scripts/bootstrap_vps.sh (it chowns both trees)." >&2
    exit 1
  fi
done

if [[ ! -f "$SRC/docker-compose.yml" ]]; then
  echo "ERROR: $SRC/docker-compose.yml not found — wrong source directory?" >&2
  exit 1
fi

# --- 2. copy source --------------------------------------------------------
if ! command -v rsync >/dev/null 2>&1; then
  echo "ERROR: rsync is required. Install it or copy the tree manually." >&2
  exit 1
fi

rsync -a --delete-excluded \
  --exclude '.git/' \
  --exclude '.venv/' \
  --exclude '__pycache__/' \
  --exclude '.pytest_cache/' \
  --exclude 'node_modules/' \
  --exclude 'dist/' \
  --exclude '.env' \
  --exclude 'runtime/' \
  "$SRC"/ "$APP_DIR"/
echo "[ok] source copied to $APP_DIR"

# --- 3. secrets: copy, never print ----------------------------------------
if [[ -f "$SRC/.env" ]]; then
  install -m 0600 "$SRC/.env" "$APP_DIR/.env"
  echo "[ok] .env copied (mode 0600, contents not displayed)"
else
  echo "[warn] $SRC/.env not found — copy .env.example and fill in values"
fi

# --- 4. compose override: host /srv/photobooth instead of a named volume ---
# Spec section 6 wants the runtime tree to live at the host path
# /srv/photobooth/{templates,tmp,cache,backups}. The base compose file uses a
# named volume so the project can run without any privileged setup; this
# override switches to the canonical host bind mounts now that they exist.
cat > "$APP_DIR/docker-compose.override.yml" <<'YAML'
# ---------------------------------------------------------------------------
# Canonical-VPS override: use the HOST /srv/photobooth runtime tree instead of
# the `photobooth_runtime` named volume (spec section 6).
#
# Generated by scripts/migrate_to_opt.sh. Requires scripts/bootstrap_vps.sh to
# have created and chowned /srv/photobooth first.
#
# To revert to the self-contained named-volume layout, delete this file.
# ---------------------------------------------------------------------------

services:
  photobooth-api:
    volumes:
      - /srv/photobooth:/srv/photobooth
      - /srv/photobooth/templates:/srv/photobooth/templates:ro

  photobooth-worker:
    volumes:
      - /srv/photobooth:/srv/photobooth
      - /srv/photobooth/templates:/srv/photobooth/templates:ro
YAML
echo "[ok] docker-compose.override.yml written (host /srv/photobooth bind mounts)"

# --- 5. validate -----------------------------------------------------------
cd "$APP_DIR"
echo
echo "== Validating compose configuration at $APP_DIR =="
if docker compose config --quiet; then
  echo "[ok] COMPOSE_CONFIG_VALID"
else
  echo "[FAIL] compose config invalid — do not start the stack" >&2
  exit 1
fi

echo
echo "== Migration prepared. Nothing was started or stopped. =="
echo
echo "The existing stack is still running and still owns:"
echo "  container names : photobooth-{api,web,worker,postgres,redis}"
echo "  network         : photobooth-net"
echo "  host ports      : 3000, 8000"
echo
echo "Because docker-compose.yml hardcodes container_name and network name, the"
echo "two checkouts CANNOT run at the same time. Choose one:"
echo
echo "  (a) Cutover (brief downtime, keeps data):"
echo "        cd $SRC      && docker compose down      # stops ONLY photobooth"
echo "        cd $APP_DIR  && docker compose up -d --build"
echo "      Postgres/Redis data survives: both use the same named volumes"
echo "      photobooth_pgdata / photobooth_redisdata."
echo
echo "  (b) Keep the current location and treat /opt/photobooth as the deploy"
echo "      target for a later release."
echo
echo "Verify after cutover:"
echo "  docker compose ps"
echo "  curl -sS http://127.0.0.1:8000/api/health"
echo "  curl -sS http://127.0.0.1:3000/api/health"
