import test from 'node:test';
import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import request from 'supertest';
import { AdminAuthModel } from '../src/models/admin-auth.model.js';
import { AdminAuthService, adminCookie } from '../src/services/admin-auth.service.js';
import { AdminDataModel } from '../src/models/admin-data.model.js';
import { AdminOperationsService } from '../src/services/admin-operations.service.js';
import { CustomerAccountModel } from '../src/models/customer-account.model.js';
import { CustomerAccountService } from '../src/services/customer-account.service.js';
import { hashCustomerPassword, tokenHash } from '../src/services/customer-credentials.service.js';
import { createMigrationApp } from '../src/migration-app.js';
import type { NativeAdminServices } from '../src/controllers/admin.controller.js';
import type { CustomerCatalogService } from '../src/services/customer-catalog.service.js';
import type { CatalogAssetsService } from '../src/services/catalog-assets.service.js';

test('PostgreSQL admin sign-in, live role revocation, admin delegation and user tier assignment',async()=>{
 const connectionString=process.env.ADMIN_TEST_DATABASE_URL;
 assert.ok(connectionString&&new URL(connectionString).pathname==='/nxbooth_express_admin_auth_test','Dedicated disposable test database required');
 const db=new PrismaClient({adapter:new PrismaPg({connectionString})});
 const password='Synthetic-admin-fixture-123';
 try{
  await db.nxAuditLog.deleteMany();await db.nxSubscription.deleteMany();await db.nxCreditLedger.deleteMany();await db.nxPlan.deleteMany();await db.nxAuthSession.deleteMany();await db.nxAuthIdentity.deleteMany();await db.nxAdminUser.deleteMany();await db.nxAccount.deleteMany();
  const hash=await hashCustomerPassword(password);
  for(const [id,email] of [['auth-owner','owner@example.invalid'],['auth-operator','operator@example.invalid'],['auth-customer','customer@example.invalid'],['auth-content','content@example.invalid'],['auth-second','second@example.invalid']])await db.nxAccount.create({data:{id,email,password_hash:hash,ai_quota_total:5}});
  for(const [id,email,role] of [['auth-owner','owner@example.invalid','superadmin'],['auth-operator','operator@example.invalid','operator'],['auth-content','content@example.invalid','content_manager']])await db.nxAdminUser.create({data:{id,email,name:id,role}});
  const account=new CustomerAccountService(new CustomerAccountModel(db),{sessionSecret:'synthetic-session-signing-key',sessionDays:1,cookieSecure:false},{async verify(credential){assert.equal(credential,'synthetic-google-verified');return {subject:'synthetic-owner',email:'owner@example.invalid',name:'Fixture owner',avatar_url:null};}});
  const auth=new AdminAuthService(new AdminAuthModel(db),account.signer,{token:'legacy-token-ignored',defaultRole:'superadmin',sessionDays:1,cookieSecure:false});
  const operations=new AdminOperationsService(new AdminDataModel(db),{} as CatalogAssetsService,{});
  const admin={auth,operations,catalog:{},usage:{},previews:{}} as NativeAdminServices;
  const app=createMigrationApp({} as CustomerCatalogService,{corsOrigins:['http://localhost:5194'],admin},account);
  const login=async(email:string)=>request(app).post('/api/admin/login').send({email,password}).expect(200);
  const cookies=(r:{headers:Record<string,unknown>})=>(r.headers['set-cookie'] as string[]).map(v=>v.split(';')[0]).join('; ');
  await request(app).get('/api/admin/me').set('x-admin-token','legacy-token-ignored').expect(401);
  await request(app).post('/api/admin/login').send({token:'legacy-token-ignored'}).expect(422);
  await request(app).post('/api/admin/login').set('Origin','https://evil.invalid').send({email:'owner@example.invalid',password}).expect(403);
  await request(app).post('/api/admin/login').send({email:'owner@example.invalid',password:'incorrect'}).expect(401);
  await request(app).post('/api/admin/login').send({email:'customer@example.invalid',password}).expect(403);
  const ownerLogin=await login('  OWNER@EXAMPLE.INVALID '),owner=cookies(ownerLogin);
  assert.match(String(ownerLogin.headers['set-cookie']),/HttpOnly/);assert.match(String(ownerLogin.headers['set-cookie']),/SameSite=Lax/);
  await request(app).get('/api/admin/me').set('Cookie',owner).expect(200).expect(r=>assert.equal(r.body.role,'superadmin'));
  await request(app).get('/api/admin/me').set('Cookie',`${adminCookie}=tampered-session`).expect(401);
  const signed=decodeURIComponent(owner.split('=').slice(1).join('=')),raw=account.signer.unsign(signed)!;
  const session=await db.nxAuthSession.findUniqueOrThrow({where:{id:tokenHash(raw)}});assert.equal(session.account_id,'auth-owner');assert.notEqual(session.id,raw);
  const operator=cookies(await login('operator@example.invalid'));
  await request(app).post('/api/admin/admin-users').set('Cookie',operator).send({id:'blocked',name:'Blocked',email:'second@example.invalid',role:'superadmin'}).expect(403);
  await request(app).post('/api/admin/admin-users').set('Cookie',owner).send({id:'auth-second',name:'Second admin',email:'second@example.invalid',role:'operator'}).expect(201);
  await request(app).post('/api/admin/admin-users').set('Cookie',owner).send({id:'duplicate',name:'Duplicate',email:'SECOND@example.invalid',role:'operator'}).expect(409);
  await request(app).post('/api/admin/admin-users').set('Cookie',owner).send({id:'unknown',name:'Unknown',email:'unregistered@example.invalid',role:'operator'}).expect(422);
  await request(app).patch('/api/admin/admin-users/auth-owner').set('Cookie',owner).send({is_active:false}).expect(409).expect(r=>assert.equal(r.body.detail.error_code,'LAST_SUPERADMIN'));
  const second=cookies(await login('second@example.invalid'));
  await request(app).patch('/api/admin/admin-users/auth-second').set('Cookie',owner).send({is_active:false}).expect(200);
  await request(app).get('/api/admin/me').set('Cookie',second).expect(401);
  await db.nxAdminUser.update({where:{id:'auth-operator'},data:{role:'content_manager'}});
  await request(app).get('/api/admin/me').set('Cookie',operator).expect(200).expect(r=>assert.equal(r.body.role,'content_manager'));
  await request(app).get('/api/admin/users').set('Cookie',operator).expect(403);
  await db.nxAccount.update({where:{id:'auth-content'},data:{status:'suspended'}});
  await request(app).post('/api/admin/login').send({email:'content@example.invalid',password}).expect(403);
  await request(app).post('/api/admin/login').send({}).expect(401);
  const google=cookies(await request(app).post('/api/account/google').send({id_token:'synthetic-google-verified'}).expect(200));
  const promoted=cookies(await request(app).post('/api/admin/login').set('Cookie',google).send({}).expect(200));
  await request(app).get('/api/admin/me').set('Cookie',promoted).expect(200);
  await request(app).post('/api/admin/login').set('Cookie',google).send({email:'customer@example.invalid'}).expect(422);
  const customer=cookies(await request(app).post('/api/account/login').send({email:'customer@example.invalid',password}).expect(200));
  await request(app).post('/api/admin/login').set('Cookie',customer).send({}).expect(403);
  await request(app).post('/api/admin/plans').set('Cookie',owner).send({id:'auth-tier',code:'auth_tier',name:'Fixture tier',monthly_ai_credits:7}).expect(201);
  await request(app).post('/api/admin/users/auth-customer/subscription').set('Cookie',owner).send({action:'assign',plan_id:'auth-tier',reason:'Admin tier test',confirm:true}).expect(200);
  assert.equal((await db.nxAccount.findUniqueOrThrow({where:{id:'auth-customer'}})).ai_quota_total,12);
  assert.equal(await db.nxCreditLedger.count({where:{user_id:'auth-customer',type:'subscription_grant'}}),1);
  await request(app).post('/api/admin/logout').set('Cookie',owner).expect(200);
  await request(app).get('/api/admin/me').set('Cookie',owner).expect(401);
  assert.ok(await db.nxAuditLog.count({where:{admin_actor_id:'auth-owner'}})>=4);
  let throttled=false;
  for(let attempt=0;attempt<20;attempt++){const r=await request(app).post('/api/admin/login').send({email:'owner@example.invalid',password:'incorrect'});if(r.status===429){throttled=true;break;}assert.equal(r.status,401);}
  assert.ok(throttled,'Repeated invalid credentials are rate limited');
 }finally{await db.$disconnect()}
});
