import { test } from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import request from 'supertest';
import { CustomerAccountModel } from '../src/models/customer-account.model.js';
import { CustomerAccountService } from '../src/services/customer-account.service.js';
import type { CustomerCatalogService } from '../src/services/customer-catalog.service.js';
import { createMigrationApp } from '../src/migration-app.js';
import { CustomerCookieSigner, tokenHash, guestCookie, accountCookie } from '../src/services/customer-credentials.service.js';
import { CreditAccountingModel } from '../src/models/credit-accounting.model.js';
import { CreditAccountingService } from '../src/services/credit-accounting.service.js';
import { CustomerResultModel } from '../src/models/customer-result.model.js';
import { CustomerResultService } from '../src/services/customer-result.service.js';
import { mkdtemp, mkdir, writeFile, rm, stat, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import sharp from 'sharp';
import { CustomerUploadModel } from '../src/models/customer-upload.model.js';
import { CustomerUploadService } from '../src/services/customer-upload.service.js';
import { CustomerGenerationService } from '../src/services/customer-generation.service.js';
import { CustomerGenerationModel } from '../src/models/customer-generation.model.js';
import { CatalogAssetsService } from '../src/services/catalog-assets.service.js';
import { ClassicImageEngineService } from '../src/services/classic-image-engine.service.js';
import { ClassicGenerationRunner } from '../src/services/classic-generation-runner.service.js';
import { CustomerGenerationWorkerService } from '../src/services/customer-generation-worker.service.js';
import { imageEngineSocketFetch } from './image-engine-socket.js';
import { extendCatalogFixture, extendApplicationFixture } from './migration-fixture-schema.js';
import { nativeApplicationIntegration } from './native-application.integration.js';

test('real PostgreSQL: native accounts, credit lifecycle, all-mode Result/QR, print and deletion', async () => {
  const connectionString = process.env.TEST_DATABASE_URL;
  assert.ok(connectionString && /^nxbooth_express_[a-z0-9_]*test$/.test(decodeURIComponent(new URL(connectionString).pathname.slice(1))), 'Use a dedicated nxbooth_express_*test database');
  assert.ok(process.env.TEST_IMAGE_ENGINE_SOCKET, 'Start a disposable image-only Python engine with a Unix socket');
  const sql = new pg.Client({ connectionString });
  const db = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });
  await sql.connect();
  const resultsDir = await mkdtemp(join(tmpdir(), 'nxbooth-express-results-'));
  const uploadsDir = await mkdtemp(join(tmpdir(), 'nxbooth-express-uploads-'));
  try {
    await sql.query(`
      CREATE TABLE accounts (id varchar(32) PRIMARY KEY, email varchar(320) NOT NULL UNIQUE, password_hash varchar(512) NOT NULL, display_name varchar(255), avatar_url varchar(1024), status varchar(24) NOT NULL DEFAULT 'active', ai_quota_total integer NOT NULL DEFAULT 5, ai_quota_used integer NOT NULL DEFAULT 0, ai_quota_reserved integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), last_login_at timestamptz, last_activity_at timestamptz);
      CREATE TABLE guest_sessions (id varchar(64) PRIMARY KEY, ai_quota_total integer NOT NULL DEFAULT 2, ai_quota_used integer NOT NULL DEFAULT 0, ai_quota_reserved integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE auth_sessions (id varchar(64) PRIMARY KEY, account_id varchar(32) REFERENCES accounts(id), is_admin boolean NOT NULL DEFAULT false, admin_user_id varchar(64), admin_role varchar(32), created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE auth_identities (id varchar(32) PRIMARY KEY, account_id varchar(32) NOT NULL REFERENCES accounts(id), provider varchar(32) NOT NULL, provider_subject varchar(255) NOT NULL, email varchar(320), created_at timestamptz NOT NULL DEFAULT now(), last_login_at timestamptz, CONSTRAINT uq_auth_identity_provider_subject UNIQUE(provider, provider_subject));
      CREATE TABLE credit_ledger (id varchar(32) PRIMARY KEY, user_id varchar(32) REFERENCES accounts(id), guest_id varchar(64) REFERENCES guest_sessions(id), amount integer NOT NULL, type varchar(64) NOT NULL, reason text NOT NULL DEFAULT '', related_generation_id varchar(32), admin_actor_id varchar(64), idempotency_key varchar(255) NOT NULL UNIQUE, metadata_json text, created_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE uploads (id varchar(32) PRIMARY KEY, account_id varchar(32) REFERENCES accounts(id), guest_id varchar(64) REFERENCES guest_sessions(id), created_at timestamptz NOT NULL DEFAULT now(), storage_path varchar(512) NOT NULL DEFAULT '', filename varchar(255) NOT NULL DEFAULT '', content_type varchar(64) NOT NULL DEFAULT 'image/jpeg', size_bytes integer NOT NULL DEFAULT 0, width integer NOT NULL DEFAULT 0, height integer NOT NULL DEFAULT 0, format varchar(16) NOT NULL DEFAULT 'JPEG', sha256 varchar(64) NOT NULL DEFAULT '', validation_status varchar(16) NOT NULL DEFAULT 'VALID', validation_detail text);
      CREATE TABLE generation_jobs (id varchar(32) PRIMARY KEY, account_id varchar(32) REFERENCES accounts(id), guest_id varchar(64) REFERENCES guest_sessions(id), mode varchar(16) NOT NULL DEFAULT 'ADVANCED', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), upload_id varchar(32) NOT NULL DEFAULT 'fixture-upload', template_id varchar(128) NOT NULL DEFAULT '', experience_id varchar(128), layout_id varchar(32), capture_upload_ids_json text, frame_style_id varchar(128), ornament_ids_json text, state varchar(16) NOT NULL DEFAULT 'QUEUED', error_code varchar(64), error_message text, provider varchar(64), model varchar(128), started_at timestamptz, finished_at timestamptz);
      CREATE TABLE quota_reservations (id varchar(32) PRIMARY KEY, job_id varchar(32) NOT NULL UNIQUE REFERENCES generation_jobs(id), account_id varchar(32) REFERENCES accounts(id), guest_id varchar(64) REFERENCES guest_sessions(id), amount integer NOT NULL DEFAULT 1, status varchar(16) NOT NULL DEFAULT 'RESERVED', created_at timestamptz NOT NULL DEFAULT now(), settled_at timestamptz);
      CREATE TABLE generation_events (id varchar(32) PRIMARY KEY, job_id varchar(32) NOT NULL REFERENCES generation_jobs(id), event_type varchar(64) NOT NULL, detail text NOT NULL DEFAULT '', metadata_json text, created_at timestamptz NOT NULL DEFAULT now());
      CREATE TABLE results (id varchar(32) PRIMARY KEY, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), job_id varchar(32) NOT NULL UNIQUE REFERENCES generation_jobs(id), template_id varchar(128) NOT NULL, storage_path varchar(512) NOT NULL, content_type varchar(64) NOT NULL, size_bytes integer NOT NULL, width integer NOT NULL, height integer NOT NULL, sha256 varchar(64) NOT NULL, provider varchar(64), model varchar(128));
      CREATE TABLE result_claims (id varchar(32) PRIMARY KEY, result_id varchar(32) NOT NULL REFERENCES results(id), token_hash varchar(64) NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, first_accessed_at timestamptz, last_accessed_at timestamptz, download_count integer NOT NULL DEFAULT 0, is_revoked boolean NOT NULL DEFAULT false, created_by_session_id varchar(128), created_by_kiosk_session_id varchar(128), metadata_json text);
      CREATE TABLE admin_templates (id varchar(128) PRIMARY KEY, name varchar(255) NOT NULL, description text NOT NULL, image_path varchar(512) NOT NULL, marketing_preview_path varchar(512), metadata_path varchar(512), enabled boolean NOT NULL, sort_order integer NOT NULL);
      CREATE TABLE admin_experiences (id varchar(128) PRIMARY KEY, name varchar(255) NOT NULL, description text NOT NULL, category varchar(64) NOT NULL, thumbnail_path varchar(512), status varchar(16) NOT NULL, enabled boolean NOT NULL, sort_order integer NOT NULL, compatible_frame_style_ids_json text, compatible_ornament_ids_json text, max_ornaments integer NOT NULL);
      CREATE TABLE classic_layouts (id varchar(32) PRIMARY KEY, slug varchar(128) NOT NULL UNIQUE, name varchar(255) NOT NULL, canvas_width integer NOT NULL, canvas_height integer NOT NULL, shot_count integer NOT NULL, layout_config_json text NOT NULL, frame_asset_path varchar(512), active boolean NOT NULL, sort_order integer NOT NULL);
      CREATE TABLE advanced_frame_styles (id varchar(128) PRIMARY KEY, slug varchar(128) NOT NULL UNIQUE, name varchar(255) NOT NULL, description text NOT NULL, enabled boolean NOT NULL, sort_order integer NOT NULL);
      CREATE TABLE advanced_ornaments (id varchar(128) PRIMARY KEY, slug varchar(128) NOT NULL UNIQUE, name varchar(255) NOT NULL, description text NOT NULL, enabled boolean NOT NULL, sort_order integer NOT NULL);
    `);
    await extendCatalogFixture(sql);
    await extendApplicationFixture(sql);
    const signer = new CustomerCookieSigner('test-only-session-secret');
    const model = new CustomerAccountModel(db);
    const service = new CustomerAccountService(model, { sessionSecret: 'test-only-session-secret', cookieSecure: false, sessionDays: 30 });
    const results = new CustomerResultService(new CustomerResultModel(db), { resultsDir, claimHours: 24, publicOrigin: 'https://nxbooth.gennexbyte.com', production: true, kioskResetSeconds: 90 });
    // Normalization test double: real HEIC/EXIF decoding is tested separately at
    // the image-engine boundary. This does not claim identity quality.
    const sourcePhoto = await sharp({ create: { width: 320, height: 480, channels: 3, background: 'blue' } }).jpeg().toBuffer();
    const uploads = new CustomerUploadService(new CustomerUploadModel(db), { async normalize() { return { bytes: sourcePhoto, width: 320, height: 480 }; } }, { uploadsDir, retentionHours: 24 });
    const root = fileURLToPath(new URL('../../', import.meta.url));
    const templatesDir = join(root, 'templates');
    const layout = JSON.parse(await readFile(join(root, 'backend/app/data/classic_original_strip_frames.json'), 'utf8')).frames[0];
    await sql.query('INSERT INTO classic_layouts VALUES ($1::text,$1::text,$2,$3,$4,$5,$6,$7,true,0)', [layout.id, layout.name, layout.canvas_width, layout.canvas_height, layout.shot_count, JSON.stringify(layout), join(templatesDir, '_classic', layout.filename)]);
    const templateId = 'sci-fi-space-commander-framed-001';
    await sql.query('INSERT INTO admin_templates VALUES ($1,$2,$3,$4,NULL,NULL,true,0)', [templateId, 'Framed', 'Fixture', join(templatesDir, templateId, 'template.png')]);
    await sql.query("INSERT INTO admin_experiences VALUES ('mini-me','Mini Me','Fixture','Design',NULL,'published',true,0,'[\"modern\"]','[\"sparkles\"]',3)");
    await sql.query("INSERT INTO advanced_frame_styles VALUES ('modern','modern','Modern','Fixture',true,0),('disabled','disabled','Disabled','Fixture',false,1)");
    await sql.query("INSERT INTO advanced_ornaments VALUES ('sparkles','sparkles','Sparkles','Fixture',true,0),('hearts','hearts','Hearts','Fixture',true,1)");
    let queueUnavailable = false;
    const queued: string[] = [];
    const generations = new CustomerGenerationService(new CustomerGenerationModel(db), uploads,
      new CatalogAssetsService([templatesDir], templatesDir), { async enqueue(id) { if (queueUnavailable) throw new Error('test queue unavailable'); queued.push(id); } });
    const app = createMigrationApp({} as CustomerCatalogService, { corsOrigins: ['http://localhost:5173'], uploadMaxBytes: 1024 * 1024 }, service, results, uploads, generations);
    const agent = request.agent(app);
    const guest = await agent.get('/api/account/usage').expect(200);
    assert.equal(guest.body.ai_remaining, 2); assert.equal(guest.body.authenticated, false);
    const setCookies = guest.headers['set-cookie'] as unknown as string[];
    assert.match(setCookies[0], /HttpOnly/); assert.match(setCookies[0], /SameSite=Lax/);
    const storedGuest = (await sql.query('SELECT id FROM guest_sessions')).rows[0].id;
    await agent.get('/api/account/me').expect(200);
    assert.equal((await sql.query('SELECT count(*)::int AS count FROM guest_sessions')).rows[0].count, 1);
    await sql.query('INSERT INTO uploads(id,account_id,guest_id) VALUES ($1,NULL,$2)', ['upload-before-signup', storedGuest]);
    await sql.query('INSERT INTO generation_jobs(id,account_id,guest_id) VALUES ($1,NULL,$2)', ['job-before-signup', storedGuest]);
    const signedUp = await agent.post('/api/account/signup').send({ email: ' User@Example.COM ', password: 'test-password-123' }).expect(201);
    assert.equal(signedUp.body.email, 'user@example.com'); assert.equal(signedUp.body.provider, 'password');
    assert.equal((await agent.get('/api/account/usage')).body.ai_remaining, 5);
    const accountId = (await sql.query('SELECT id FROM accounts')).rows[0].id;
    const ledger = (await sql.query('SELECT amount,type,idempotency_key FROM credit_ledger')).rows;
    assert.deepEqual(ledger, [{ amount: 5, type: 'signup_bonus', idempotency_key: `signup_bonus:password:${accountId}` }]);
    assert.deepEqual((await sql.query('SELECT account_id,guest_id FROM uploads')).rows, [{ account_id: accountId, guest_id: null }]);
    assert.deepEqual((await sql.query('SELECT account_id,guest_id FROM generation_jobs')).rows, [{ account_id: accountId, guest_id: null }]);
    await agent.post('/api/account/signup').send({ email: 'user@example.com', password: 'test-password-123' }).expect(409);
    assert.equal((await sql.query('SELECT count(*)::int AS count FROM credit_ledger')).rows[0].count, 1);
    await agent.patch('/api/account/profile').send({ display_name: '  NX Tester  ' }).expect(200).expect(response => assert.equal(response.body.display_name, 'NX Tester'));
    await request(app).post('/api/account/login').send({ email: 'user@example.com', password: 'wrong-password' }).expect(401);
    await request(app).post('/api/account/login').set('Origin', 'https://untrusted.example').send({ email: 'user@example.com', password: 'test-password-123' }).expect(403);
    const malformed = await request(app).post('/api/account/login').set('Content-Type', 'application/json').send('{').expect(400);
    assert.match(malformed.headers['cache-control'], /no-store/);
    await agent.post('/api/account/logout').expect(200).expect(response => assert.equal(response.body.authenticated, false));
    assert.equal((await agent.get('/api/account/me')).body.authenticated, false);
    await agent.post('/api/account/login').send({ email: 'USER@example.com', password: 'test-password-123' }).expect(200);
    const sessionId = (await sql.query('SELECT id FROM auth_sessions WHERE is_admin=false')).rows[0].id;
    assert.equal(sessionId.length, 64);
    const other = request.agent(app);
    await other.post('/api/account/signup').send({ email: 'other@example.com', password: 'test-password-456' }).expect(201);
    await other.post(`/api/account/sessions/${sessionId}/revoke`).expect(404);
    await agent.post(`/api/account/sessions/${sessionId}/revoke`).expect(200).expect(response => assert.equal(response.body.current, true));
    assert.equal((await agent.get('/api/account/me')).body.authenticated, false);
    // An old signed token and SHA-256 session row remain usable without reissuing it.
    const legacyRaw = 'legacy-customer-session';
    await sql.query('INSERT INTO auth_sessions(id,account_id,expires_at) VALUES ($1,$2,now()+interval \'1 day\')', [tokenHash(legacyRaw), accountId]);
    await request(app).get('/api/account/me').set('Cookie', `${accountCookie}=${signer.sign(legacyRaw)}`).expect(200).expect(response => assert.equal(response.body.authenticated, true));
    await sql.query("UPDATE accounts SET status='suspended' WHERE id=$1", [accountId]);
    await request(app).post('/api/account/login').send({ email: 'user@example.com', password: 'test-password-123' }).expect(403);
    await request(app).get('/api/account/usage').set('Cookie', `${guestCookie}=${signer.sign(storedGuest)}`).expect(200).expect(response => assert.equal(response.body.ai_remaining, 2));
    const credits = new CreditAccountingService(new CreditAccountingModel(db));
    await sql.query("UPDATE accounts SET status='active',ai_quota_total=1 WHERE id=$1", [accountId]);
    for (const id of ['basic-first', 'advanced-first', 'advanced-second', 'advanced-refund']) await sql.query('INSERT INTO generation_jobs(id,account_id,guest_id) VALUES ($1,$2,NULL)', [id, accountId]);
    const owner = { account_id: accountId, guest_id: null };
    assert.equal(await credits.reserve('CLASSIC', 'job-before-signup', owner), null);
    assert.ok(await credits.reserve('BASIC', 'basic-first', owner));
    assert.equal((await sql.query('SELECT count(*)::int AS count FROM quota_reservations')).rows[0].count, 1);
    const reserved = await Promise.allSettled(['advanced-first', 'advanced-second'].map(id => credits.reserve('ADVANCED', id, owner)));
    assert.equal(reserved.filter(item => item.status === 'fulfilled').length, 0);
    assert.equal(reserved.filter(item => item.status === 'rejected').length, 2);
    const jobId = 'basic-first';
    const completed = await Promise.all([credits.settle(jobId, true), credits.settle(jobId, true)]);
    assert.equal(completed.filter(Boolean).length, 1);
    assert.equal(await credits.settle(jobId, false), false);
    assert.deepEqual((await sql.query('SELECT ai_quota_used,ai_quota_reserved FROM accounts WHERE id=$1', [accountId])).rows[0], { ai_quota_used: 1, ai_quota_reserved: 0 });
    assert.equal((await sql.query("SELECT count(*)::int AS count FROM credit_ledger WHERE type='generation_spend'")).rows[0].count, 1);
    await sql.query('UPDATE accounts SET ai_quota_total=2 WHERE id=$1', [accountId]);
    await credits.reserve('ADVANCED', 'advanced-refund', owner);
    assert.equal(await credits.settle('advanced-refund', false), true);
    assert.equal(await credits.settle('advanced-refund', false), false);
    assert.deepEqual((await sql.query('SELECT ai_quota_used,ai_quota_reserved FROM accounts WHERE id=$1', [accountId])).rows[0], { ai_quota_used: 1, ai_quota_reserved: 0 });
    assert.equal((await sql.query("SELECT count(*)::int AS count FROM credit_ledger WHERE type='generation_refund'")).rows[0].count, 1);
    await sql.query('UPDATE accounts SET ai_quota_total=3 WHERE id=$1', [accountId]);
    const ownerCookie = `${accountCookie}=${signer.sign(legacyRaw)}`;
    const uploaded = await request(app).post('/api/uploads').set('Cookie', ownerCookie).attach('file', sourcePhoto, 'native-photo.jpg').expect(201);
    assert.equal(uploaded.body.normalized_content_type, 'image/jpeg');
    assert.equal(uploaded.body.validation_status, 'VALID');
    assert.deepEqual([uploaded.body.width, uploaded.body.height], [320, 480]);
    const uploadId = uploaded.body.upload_id;
    await request(app).get(`/api/uploads/${uploadId}`).set('Cookie', ownerCookie).expect(200).expect(response => assert.equal(response.body.upload_id, uploadId));
    await request(app).get(`/api/uploads/${uploadId}`).expect(404);
    const recoveredPreview = await request(app).get(`/api/uploads/${uploadId}/preview`).set('Cookie', ownerCookie).expect(200);
    assert.deepEqual(recoveredPreview.body, sourcePhoto);
    await request(app).post('/api/uploads').set('Cookie', ownerCookie).expect(400);
    await request(app).post('/api/uploads').set('Cookie', ownerCookie).attach('file', Buffer.alloc(1024 * 1024 + 1), 'too-large.jpg').expect(413);
    assert.equal((await request(app).get('/api/account/usage').set('Cookie', ownerCookie)).body.ai_reserved, 0);
    const captureIds = [uploadId];
    for (let i = 1; i < layout.shot_count; i++) captureIds.push((await request(app).post('/api/uploads').set('Cookie', ownerCookie).attach('file', sourcePhoto, 'capture.jpg').expect(201)).body.upload_id);
    const classicInput = { mode: 'CLASSIC', upload_id: uploadId, layout_id: layout.id, capture_upload_ids: captureIds };
    const classic = (await request(app).post('/api/generations').set('Cookie', ownerCookie).send(classicInput).expect(202)).body;
    assert.equal(classic.state, 'QUEUED'); assert.equal(classic.layout_id, layout.id);
    assert.deepEqual(JSON.parse((await db.nxGenerationJob.findUniqueOrThrow({ where: { id: classic.job_id } })).capture_upload_ids_json!), captureIds);
    await request(app).post('/api/generations').set('Cookie', ownerCookie).send({ ...classicInput, capture_upload_ids: [uploadId] }).expect(422);
    await request(app).post('/api/generations').set('Cookie', ownerCookie).send({ ...classicInput, capture_upload_ids: captureIds.map(() => uploadId) }).expect(422);
    await request(app).post('/api/generations').set('Cookie', ownerCookie).send({ ...classicInput, frame_style_id: 'modern' }).expect(422);
    const basic = (await request(app).post('/api/generations').set('Cookie', ownerCookie).send({ mode: 'BASIC', upload_id: uploadId, template_id: templateId }).expect(202)).body;
    assert.equal(basic.template_id, templateId);
    assert.equal((await db.nxQuotaReservation.count({ where: { job_id: { in: [classic.job_id, basic.job_id] } } })), 1);
    const advancedInput = { mode: 'ADVANCED', upload_id: uploadId, experience_id: 'mini-me', frame_style_id: 'modern', ornament_ids: ['sparkles'] };
    for (const invalid of [{ frame_style_id: 'unknown' }, { frame_style_id: 'disabled' }, { ornament_ids: ['hearts'] }, { ornament_ids: ['unknown'] }, { ornament_ids: ['sparkles', 'sparkles'] }]) await request(app).post('/api/generations').set('Cookie', ownerCookie).send({ ...advancedInput, ...invalid }).expect(422);
    const advanced = (await request(app).post('/api/generations').set('Cookie', ownerCookie).send(advancedInput).expect(202)).body;
    assert.deepEqual(advanced.ornament_ids, ['sparkles']); assert.equal(advanced.frame_style_id, 'modern');
    const recovered = (await request(app).get(`/api/generations/${advanced.job_id}`).set('Cookie', ownerCookie).expect(200)).body;
    assert.equal(recovered.upload_id, uploadId); assert.equal(recovered.frame_style_id, 'modern'); assert.deepEqual(recovered.ornament_ids, ['sparkles']);
    assert.equal(recovered.result_id, null);
    await request(app).get(`/api/generations/${advanced.job_id}`).expect(404);
    const beforeRejected = await db.nxGenerationJob.count();
    await request(app).post('/api/generations').set('Cookie', ownerCookie).send(advancedInput).expect(403);
    assert.equal(await db.nxGenerationJob.count(), beforeRejected); // Quota failure rolls back the job.
    await credits.settle(advanced.job_id, false);
    queueUnavailable = true;
    await request(app).post('/api/generations').set('Cookie', ownerCookie).send(advancedInput).expect(503);
    assert.equal((await request(app).get('/api/account/usage').set('Cookie', ownerCookie)).body.ai_reserved, 1); // Basic is still queued and reserves its own credit.
    const failedQueue = await db.nxGenerationJob.findFirstOrThrow({ where: { error_code: 'QUEUE_UNAVAILABLE' } });
    assert.equal(failedQueue.state, 'FAILED');
    assert.equal((await db.nxQuotaReservation.findUniqueOrThrow({ where: { job_id: failedQueue.id } })).status, 'REFUNDED');
    await credits.settle(basic.job_id, false);
    assert.equal((await request(app).get('/api/account/usage').set('Cookie', ownerCookie)).body.ai_reserved, 0);
    await sql.query("UPDATE generation_jobs SET state='FAILED' WHERE id=$1", [basic.job_id]);
    assert.deepEqual(queued, [classic.job_id, basic.job_id, advanced.job_id]);
    // Expired secondary Classic captures must remain while their job is active.
    await sql.query("UPDATE uploads SET created_at=now()-interval '25 hours' WHERE id=$1", [captureIds[1]]);
    assert.equal((await uploads.cleanup()).active_jobs_skipped, 1);
    // Make that capture available again for real Pillow composition below.
    await sql.query('UPDATE uploads SET created_at=now() WHERE id=$1', [captureIds[1]]);
    const generationModel = new CustomerGenerationModel(db);
    const classicRunner = new ClassicGenerationRunner(generationModel, uploads, new CatalogAssetsService([templatesDir], templatesDir),
      new ClassicImageEngineService('http://image-engine.test/compose-classic', 'test-only-engine-key', imageEngineSocketFetch(process.env.TEST_IMAGE_ENGINE_SOCKET!)));
    const classicWorker = new CustomerGenerationWorkerService(generationModel, classicRunner, resultsDir);
    const processed = await Promise.all([classicWorker.process(classic.job_id), classicWorker.process(classic.job_id)]);
    assert.equal(processed.filter(Boolean).length, 1); // Duplicate delivery never creates a second Result.
    const completedClassic = (await request(app).get(`/api/generations/${classic.job_id}`).set('Cookie', ownerCookie).expect(200)).body;
    assert.equal(completedClassic.state, 'COMPLETED'); assert.ok(completedClassic.result_id);
    const composed = await request(app).get(`/api/results/${completedClassic.result_id}/image`).set('Cookie', ownerCookie).expect(200);
    const compositeInfo = await sharp(composed.body).metadata();
    assert.deepEqual([compositeInfo.width, compositeInfo.height, compositeInfo.density], [1200, 3600, 600]);
    assert.equal((await db.nxQuotaReservation.count({ where: { job_id: classic.job_id } })), 0);
    const classicClaim = await request(app).post(`/api/results/${completedClassic.result_id}/claim`).set('Cookie', ownerCookie).send({}).expect(200);
    await request(app).get(`/api/public/results/${classicClaim.body.claim_url.split('/r/')[1]}`).expect(200);
    // Real database test of FAILED + credit refund transaction. The malformed
    // image is an engine test double, never a real Basic/Advanced generation.
    queueUnavailable = false;
    const failAdvanced = (await request(app).post('/api/generations').set('Cookie', ownerCookie).send(advancedInput).expect(202)).body;
    const badWorker = new CustomerGenerationWorkerService(generationModel, { async generate() { return { bytes: Buffer.from('not a PNG'), provider: 'test', model: 'test-only' }; } }, resultsDir);
    assert.equal(await badWorker.process(failAdvanced.job_id), false);
    assert.equal((await db.nxGenerationJob.findUniqueOrThrow({ where: { id: failAdvanced.job_id } })).state, 'FAILED');
    assert.equal((await db.nxQuotaReservation.findUniqueOrThrow({ where: { job_id: failAdvanced.job_id } })).status, 'REFUNDED');
    assert.equal(await db.nxResult.count({ where: { job_id: failAdvanced.job_id } }), 0);
    assert.equal((await request(app).get('/api/account/usage').set('Cookie', ownerCookie)).body.ai_reserved, 0);
    await sql.query("UPDATE uploads SET created_at=now()-interval '25 hours' WHERE id=$1", [captureIds[1]]);
    const successAdvanced = (await request(app).post('/api/generations').set('Cookie', ownerCookie).send(advancedInput).expect(202)).body;
    const syntheticAdvanced = await sharp({ create: { width: 2160, height: 3240, channels: 3, background: 'orange' } }).png().toBuffer();
    // This verifies worker/database/credits only; the synthetic bytes are not an
    // AI output and establish neither provider health nor identity quality.
    const successWorker = new CustomerGenerationWorkerService(generationModel, { async generate() { return { bytes: syntheticAdvanced, provider: 'test', model: 'test-only' }; } }, resultsDir);
    assert.equal(await successWorker.process(successAdvanced.job_id), true);
    assert.equal(await successWorker.process(successAdvanced.job_id), false);
    assert.equal((await db.nxQuotaReservation.findUniqueOrThrow({ where: { job_id: successAdvanced.job_id } })).status, 'CONSUMED');
    assert.equal(await db.nxResult.count({ where: { job_id: successAdvanced.job_id } }), 1);
    assert.equal(await db.nxCreditLedger.count({ where: { related_generation_id: successAdvanced.job_id, type: 'generation_spend' } }), 1);
    assert.equal((await request(app).get('/api/account/usage').set('Cookie', ownerCookie)).body.ai_reserved, 0);
    assert.equal((await request(app).get('/api/account/usage').set('Cookie', ownerCookie)).body.ai_used, 2);
    await sql.query("UPDATE generation_jobs SET state='FAILED' WHERE state='QUEUED' AND id IN ($1,$2)", [classic.job_id, advanced.job_id]);
    assert.equal((await uploads.cleanup()).metadata_scrubbed, 1);
    await sql.query("UPDATE uploads SET created_at=now()-interval '25 hours' WHERE id=$1", [uploadId]);
    await request(app).get(`/api/uploads/${uploadId}`).set('Cookie', ownerCookie).expect(410);
    const removed = await uploads.cleanup();
    assert.equal(removed.files_removed, 1); assert.equal(removed.metadata_scrubbed, 1);
    assert.equal((await db.nxUpload.findUniqueOrThrow({ where: { id: uploadId } })).validation_status, 'EXPIRED');
    for (const [index, mode] of ['CLASSIC', 'BASIC', 'ADVANCED'].entries()) {
      const id = ['c', 'b', 'a'][index].repeat(32);
      const jobId = `delivery-${mode.toLowerCase()}`;
      const width = mode === 'CLASSIC' ? 1200 : 32;
      const height = mode === 'CLASSIC' ? 3600 : 48;
      // Synthetic solid image, never a real customer photo or a generated AI result.
      const bytes = await sharp({ create: { width, height, channels: 4, background: 'orange' } }).withMetadata({ density: 600 }).png().toBuffer();
      await mkdir(join(resultsDir, id.slice(0, 2)), { recursive: true });
      const path = join(resultsDir, id.slice(0, 2), `${id}.png`);
      await writeFile(path, bytes);
      await sql.query('INSERT INTO generation_jobs(id,account_id,guest_id,mode) VALUES ($1,$2,NULL,$3)', [jobId, accountId, mode]);
      await sql.query("INSERT INTO results(id,job_id,template_id,storage_path,content_type,size_bytes,width,height,sha256) VALUES ($1,$2,$3,$4,'image/png',$5,$6,$7,$8)", [id, jobId, 'sci-fi-space-commander-framed-001', path, bytes.length, width, height, createHash('sha256').update(bytes).digest('hex')]);
      const metadata = await request(app).get(`/api/results/${id}`).set('Cookie', ownerCookie).expect(200);
      assert.equal(metadata.body.result_id, id);
      assert.equal(Boolean(metadata.body.print_download_url), mode === 'CLASSIC');
      await request(app).get(`/api/results/${id}`).expect(404);
      const image = await request(app).get(`/api/results/${id}/image`).set('Cookie', ownerCookie).expect(200);
      assert.deepEqual(image.body, bytes);
      const claim = await request(app).post(`/api/results/${id}/claim`).set('Cookie', ownerCookie).send({}).expect(200);
      const token = claim.body.claim_url.split('/r/')[1];
      assert.equal(claim.body.claim_url, claim.body.qr_payload);
      const stored = (await sql.query('SELECT token_hash FROM result_claims WHERE result_id=$1', [id])).rows[0].token_hash;
      assert.equal(stored, tokenHash(token)); assert.notEqual(stored, token);
      await request(app).post(`/api/results/${id}/claim`).set('Cookie', ownerCookie).send({}).expect(409);
      const reuse = await request(app).post(`/api/results/${id}/claim`).set('Cookie', ownerCookie).send({ reuse_token: token }).expect(200);
      assert.equal(reuse.body.claim_url, claim.body.claim_url);
      await request(app).get(`/api/public/results/${token}`).expect(200).expect(response => assert.equal(response.body.width, width));
      const publicImage = await request(app).get(`/api/public/results/${token}/image`).expect(200);
      assert.deepEqual(publicImage.body, bytes);
      await Promise.all([1, 2, 3].map(() => request(app).get(`/api/public/results/${token}/download`).expect(200)));
      assert.equal((await sql.query('SELECT download_count FROM result_claims WHERE token_hash=$1', [tokenHash(token)])).rows[0].download_count, 3);
      if (mode === 'CLASSIC') {
        const printed = await request(app).get(`/api/public/results/${token}/download?rendition=print`).expect(200);
        const info = await sharp(printed.body).metadata();
        assert.deepEqual([info.width, info.height, info.density], [600, 1800, 300]);
        await request(app).get(`/api/results/${id}/download?rendition=print`).set('Cookie', ownerCookie).expect(200);
      } else await request(app).get(`/api/public/results/${token}/download?rendition=print`).expect(422);
      const refreshed = await request(app).post(`/api/results/${id}/claim`).set('Cookie', ownerCookie).send({ refresh: true }).expect(200);
      await request(app).get(`/api/public/results/${token}`).expect(404);
      const fresh = refreshed.body.claim_url.split('/r/')[1];
      await sql.query("UPDATE result_claims SET expires_at=now()-interval '1 minute' WHERE token_hash=$1", [tokenHash(fresh)]);
      await request(app).get(`/api/public/results/${fresh}`).expect(404);
      await request(app).post(`/api/results/${id}/claim`).set('Cookie', ownerCookie).send({}).expect(409);
      await request(app).delete(`/api/results/${id}`).set('Cookie', ownerCookie).send({ confirm: false }).expect(422);
      await request(app).delete(`/api/results/${id}`).set('Cookie', ownerCookie).send({ confirm: true }).expect(200);
      await assert.rejects(stat(path));
      await request(app).get(`/api/results/${id}`).set('Cookie', ownerCookie).expect(404);
      assert.equal((await sql.query('SELECT count(*)::int AS count FROM result_claims WHERE result_id=$1 AND is_revoked=false', [id])).rows[0].count, 0);
      assert.ok((await sql.query('SELECT deleted_at FROM results WHERE id=$1', [id])).rows[0].deleted_at);
    }
    const kioskSession = await request(app).post('/api/kiosk/session?new_run=true').expect(200);
    assert.equal(kioskSession.body.reset_after_seconds, 90);
    assert.match((kioskSession.headers['set-cookie'] as unknown as string[])[0], /HttpOnly/);
    await nativeApplicationIntegration(db,sql,root,resultsDir,uploadsDir,accountId,ownerCookie);
  } finally {
    await db.$disconnect();
    await sql.query('DROP TABLE IF EXISTS generation_worker_leases, generation_provider_runs, subscriptions, subscription_plans, admin_audit_log, auth_identities, auth_sessions, admin_users, credit_ledger, event_basic_templates, event_advanced_experiences, uploads, result_claims, results, generation_events, quota_reservations, generation_jobs, kiosk_sessions, events, accounts, guest_sessions');
    await sql.query('DROP TABLE IF EXISTS preview_generation_jobs, preview_sources');
    await sql.query('DROP TABLE IF EXISTS admin_templates, admin_experiences, classic_layouts, advanced_frame_styles, advanced_ornaments');
    await sql.end();
    await rm(resultsDir, { recursive: true, force: true });
    await rm(uploadsDir, { recursive: true, force: true });
  }
});
