import test from 'node:test';import assert from 'node:assert/strict';import {PrismaClient} from '@prisma/client';import {PrismaPg} from '@prisma/adapter-pg';import {randomBytes,randomUUID} from 'node:crypto';import {mkdtemp,mkdir,copyFile,readFile,writeFile,rm} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import sharp from 'sharp';import request from 'supertest';
import {CustomerGenerationModel} from '../src/models/customer-generation.model.js';import {CustomerGenerationService} from '../src/services/customer-generation.service.js';import {CustomerGenerationWorkerService} from '../src/services/customer-generation-worker.service.js';import {ClassicGenerationRunner} from '../src/services/classic-generation-runner.service.js';import {ClassicImageEngineService} from '../src/services/classic-image-engine.service.js';import {CustomerUploadModel} from '../src/models/customer-upload.model.js';import {CustomerUploadService} from '../src/services/customer-upload.service.js';import {CustomerAccountModel} from '../src/models/customer-account.model.js';import {CustomerAccountService} from '../src/services/customer-account.service.js';import {CustomerResultModel} from '../src/models/customer-result.model.js';import {CustomerResultService} from '../src/services/customer-result.service.js';import {CustomerCatalogModel} from '../src/models/customer-catalog.model.js';import {CustomerCatalogService} from '../src/services/customer-catalog.service.js';import {CatalogAssetsService} from '../src/services/catalog-assets.service.js';import {hashCustomerPassword} from '../src/services/customer-credentials.service.js';import {createMigrationApp} from '../src/migration-app.js';
test('Real personalized Classic pipeline, embedded QR and paid delivery',async()=>{
 const connectionString=process.env.CREDIT_TEST_DATABASE_URL;assert.ok(connectionString&&new URL(connectionString).pathname==='/nxbooth_credit_test');assert.ok(process.env.FLORAL_HELPER_URL);
 const db=new PrismaClient({adapter:new PrismaPg({connectionString})});const dir=await mkdtemp('/srv/photobooth/tmp/floral-integration-');
 try{
  const source=process.env.CLASSIC_TEST_ASSET||'../backend/app/data/classic-floral-event-001';assert.ok(/^\.\.\/backend\/app\/data\/(classic-floral-event-001|classic-personalized-v3\/classic-[a-z0-9-]+)$/.test(source));
  const root=dir+'/templates';await mkdir(root);await copyFile(source+'/blank.png',root+'/blank.png');const config=JSON.parse(await readFile(source+'/layout.json','utf8'));
  const layout=await db.nxClassicLayout.create({data:{id:config.id,slug:config.id,name:config.name||'Blue Floral Event',canvas_width:1200,canvas_height:3600,shot_count:3,layout_config_json:JSON.stringify({slots:config.slots,event_personalization:config.event_personalization===true}),frame_asset_path:root+'/blank.png',active:true,sort_order:-1}});
  const assets=new CatalogAssetsService([dir],root);const am=new CustomerAccountModel(db);const password='Synthetic-Floral-123';const account=await am.signup('floral-'+Date.now()+'@example.invalid',await hashCustomerPassword(password),null);
  const uploads=new CustomerUploadService(new CustomerUploadModel(db),{} as never,{uploadsDir:dir,retentionHours:24});const captures=[];
  for(const color of ['red','green','blue']){const id=randomBytes(16).toString('hex');const bytes=await sharp({create:{width:600,height:900,channels:3,background:color}}).jpeg().toBuffer();const path=dir+'/'+id+'.jpg';await writeFile(path,bytes);captures.push(await db.nxUpload.create({data:{id,account_id:account.id,storage_path:path,filename:'fixture.jpg',content_type:'image/jpeg',size_bytes:bytes.length,width:600,height:900,format:'JPEG',sha256:'0'.repeat(64)}}));}
  const queued:string[]=[];const model=new CustomerGenerationModel(db);const generations=new CustomerGenerationService(model,uploads,assets,{async enqueue(id){queued.push(id)}});const accounts=new CustomerAccountService(am,{sessionSecret:'synthetic-floral-session',sessionDays:1,cookieSecure:false});const results=new CustomerResultService(new CustomerResultModel(db),{resultsDir:dir+'/results',claimHours:24,publicOrigin:'https://nxbooth.gennexbyte.com',production:true});const catalog=new CustomerCatalogService(new CustomerCatalogModel(db),assets);const app=createMigrationApp(catalog,{corsOrigins:[]},accounts,results,uploads,generations);
  const login=await request(app).post('/api/account/login').send({email:account.email,password}).expect(200);const cookie=(login.headers['set-cookie'] as unknown as string[]).map(v=>v.split(';')[0]).join('; ');
  const body={mode:'CLASSIC',layout_id:layout.id,upload_id:captures[0].id,capture_upload_ids:captures.map(row=>row.id),captured_at:new Date(captures[0].created_at.getTime()-1000).toISOString(),event_name:'Pernikahan Sarah & Arif'};
  const listing=await request(app).get('/api/classic/layouts').expect(200);assert.equal(listing.body.find((r:{id:string})=>r.id===layout.id).requires_event_name,true);
  await request(app).post('/api/generations').set('Cookie',cookie).send({...body,event_name:undefined}).expect(422);await request(app).post('/api/generations').set('Cookie',cookie).send({...body,event_name:'A\nB'}).expect(422);await request(app).post('/api/generations').set('Cookie',cookie).send({...body,captured_at:'2020-01-01T00:00:00.000Z'}).expect(422);
  const key=randomUUID();const started=await request(app).post('/api/generations').set('Cookie',cookie).set('Idempotency-Key',key).send(body).expect(202);const retry=await request(app).post('/api/generations').set('Cookie',cookie).set('Idempotency-Key',key).send(body).expect(202);assert.equal(retry.body.job_id,started.body.job_id);assert.equal(queued.length,1);assert.equal((await am.wallet(account.id)).free_remaining,50);
  await request(app).post('/api/generations').set('Cookie',cookie).set('Idempotency-Key',key).send({...body,event_name:'Different event'}).expect(409);
  const worker=new CustomerGenerationWorkerService(model,new ClassicGenerationRunner(model,uploads,assets,new ClassicImageEngineService(process.env.FLORAL_HELPER_URL!,'synthetic-floral-test-key')),dir+'/results');assert.equal(await worker.process(started.body.job_id),true);assert.equal((await am.wallet(account.id)).free_remaining,49);assert.equal(await worker.process(started.body.job_id),false);
  const result=await db.nxResult.findUniqueOrThrow({where:{job_id:started.body.job_id}});const bytes=await readFile(result.storage_path);const info=await sharp(bytes).metadata();assert.equal(info.width,1200);assert.equal(info.height,3600);assert.equal(info.channels,3);
  const decode=(path:string)=>execFileSync('/srv/photobooth/tmp/event-template-venv/bin/python',['-c','from PIL import Image;import zxingcpp,sys;print(zxingcpp.read_barcode(Image.open(sys.argv[1])).text)',path],{encoding:'utf8'}).trim();const qr=decode(result.storage_path),token=new URL(qr).pathname.slice(3);
  const claim=await request(app).post(`/api/results/${result.id}/claim`).set('Cookie',cookie).send({}).expect(200);assert.equal(claim.body.claim_url,qr);const refreshed=await request(app).post(`/api/results/${result.id}/claim`).set('Cookie',cookie).send({refresh:true}).expect(200);assert.equal(refreshed.body.claim_url,qr);assert.equal(new Date(claim.body.expires_at).getTime()-result.created_at.getTime(),14*86400000);
  await request(app).get(`/api/public/results/${token}`).expect(200);const download=await request(app).get(`/api/public/results/${token}/download`).expect(200);assert.deepEqual(download.body,bytes);const print=await request(app).get(`/api/public/results/${token}/download?rendition=print`).expect(200);const pi=await sharp(print.body).metadata();assert.equal(pi.width,600);assert.equal(pi.height,1800);const pp=dir+'/print.png';await writeFile(pp,print.body);assert.equal(decode(pp),qr);assert.equal(await db.nxProviderRun.count({where:{account_id:account.id}}),0);
  await request(app).delete(`/api/results/${result.id}`).set('Cookie',cookie).send({confirm:true}).expect(200);await request(app).get(`/api/public/results/${token}/download`).expect(404);assert.equal((await am.wallet(account.id)).free_remaining,49);
  console.log('PASS real Python composition; 1 credit after result; printed QR decodes/downloads master and print; no AI calls; deletion revokes QR');
 }finally{await db.$disconnect();await rm(dir,{recursive:true,force:true})}
});
